#**One hot encoding**

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#sample categorical data
data = np.array([['red'], ['blue'], ['green'], ['red'], ['blue']])

#Initialize the one hot encoder
encoder = OneHotEncoder(sparse_output=False)

#Fit and transform the data
encoded_data = encoder.fit_transform(data)

#Print the encoded data
print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


#**Bag Of Words(BOW)**

In [2]:
import numpy as np
import pandas as pd


In [3]:
df = pd.DataFrame({
    "text":["people watch ds with bappy",
            "ds with bappy watch ds with bappy",
            "people write comment",
            "ds with bappy write comment"],"output":[1,1,0,0]
})
df

text  output
0         people watch ds with bappy       1
1  ds with bappy watch ds with bappy       1
2               people write comment       0
3        ds with bappy write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df["text"])

In [5]:
bow.toarray()

array([[1, 0, 1, 1, 1, 1, 0],
       [2, 0, 2, 0, 1, 2, 0],
       [0, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 1]])

In [6]:
#Vocabulary
print(cv.vocabulary_)

{'people': 3, 'watch': 4, 'ds': 2, 'with': 5, 'bappy': 0, 'write': 6, 'comment': 1}


#N-Grams

In [7]:
df = pd.DataFrame({
    "text":["people watch ds with bappy",
            "ds with bappy watch ds with bappy",
            "people write comment",
            "ds with bappy write comment"],"output":[1,1,0,0]
})
df

text  output
0         people watch ds with bappy       1
1  ds with bappy watch ds with bappy       1
2               people write comment       0
3        ds with bappy write comment       0

In [8]:
#Bi grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))
bow = cv.fit_transform(df["text"])
bow.toarray()

array([[0, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 2, 0, 0, 1, 2, 0],
       [0, 0, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1]])

#**TF-IDF**

In [9]:
df = pd.DataFrame({
    "text":["people watch ds with bappy",
            "ds with bappy watch ds with bappy",
            "people write comment",
            "ds with bappy write comment"],"output":[1,1,0,0]
})
df

text  output
0         people watch ds with bappy       1
1  ds with bappy watch ds with bappy       1
2               people write comment       0
3        ds with bappy write comment       0

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
arr = tf.fit_transform(df["text"]).toarray()

In [11]:
arr

array([[0.40650968, 0.        , 0.40650968, 0.50212033, 0.50212033,
        0.40650968, 0.        ],
       [0.54381334, 0.        , 0.54381334, 0.        , 0.33585883,
        0.54381334, 0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027],
       [0.40650968, 0.50212033, 0.40650968, 0.        , 0.        ,
        0.40650968, 0.50212033]])

#**WORD_2_VEC**

In [13]:
!pip install gensim

In [14]:
import numpy as np
import pandas as pd
import gensim
import os

In [16]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punk_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading punk_tab: Package 'punk_tab' not found in
[nltk_data]     index


False

In [19]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [21]:
story=[]
for filename in os.listdir('/content/Data/'):
  filepath = os.path.join('/content/Data', filename)
  if os.path.isfile(filepath):
    f = open(filepath)
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
      story.append(simple_preprocess(sent))

In [22]:
story

[['this',
  'edition',
  'contains',
  'the',
  'complete',
  'text',
  'of',
  'the',
  'original',
  'hardcover',
  'edition'],
 ['not', 'one', 'word', 'has', 'been', 'omitted'],
 ['clash',
  'of',
  'kings',
  'bantam',
  'spectra',
  'book',
  'publishing',
  'history',
  'bantam',
  'spectra',
  'hardcover',
  'edition',
  'published',
  'february',
  'bantam',
  'spectra',
  'paperback',
  'edition',
  'september',
  'spectra',
  'and',
  'the',
  'portrayal',
  'of',
  'boxed',
  'are',
  'trademarks',
  'of',
  'bantam',
  'books',
  'division',
  'of',
  'random',
  'house',
  'inc',
  'all',
  'rights',
  'reserved'],
 ['copyright', 'by', 'george', 'martin'],
 ['maps', 'by', 'james', 'sinclair'],
 ['heraldic', 'crest', 'by', 'virginia', 'norey'],
 ['library', 'of', 'congress', 'catalog', 'card', 'number'],
 ['no',
  'part',
  'of',
  'this',
  'book',
  'may',
  'be',
  'reproduced',
  'or',
  'transmitted',
  'in',
  'any',
  'form',
  'or',
  'by',
  'any',
  'means',
  'el

In [23]:
len(story)

23532

In [24]:
#Model

model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [25]:
model.build_vocab(story)

In [26]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(1181033, 1572525)

In [27]:
vec = model.wv.get_normed_vectors()

In [28]:
vec

array([[-0.19392763, -0.00621538,  0.14099638, ..., -0.02724126,
         0.002408  ,  0.08949457],
       [-0.2787315 ,  0.11046539,  0.1010306 , ...,  0.02173545,
         0.02250512,  0.11053503],
       [-0.02452476,  0.24951679, -0.08211673, ..., -0.07453985,
         0.0820425 , -0.13817209],
       ...,
       [-0.20839173,  0.1857029 ,  0.05290861, ..., -0.04974138,
         0.00968118, -0.02720923],
       [-0.10424561,  0.1957446 ,  0.11037537, ...,  0.02689849,
         0.0004507 ,  0.09787396],
       [-0.225243  ,  0.1513391 ,  0.11199041, ..., -0.00187611,
         0.0165968 ,  0.05000504]], dtype=float32)

In [29]:
len(vec[0])

100

In [30]:
model.wv.most_similar("arya")

[('feel', 0.9659882187843323),
 ('herself', 0.9543534517288208),
 ('breathe', 0.9519103765487671),
 ('knock', 0.9490503668785095),
 ('bran', 0.9439638257026672),
 ('something', 0.9400216341018677),
 ('moment', 0.9382168650627136),
 ('she', 0.9360185861587524),
 ('tried', 0.9348317384719849),
 ('gendry', 0.9341669082641602)]

In [36]:
y = model.wv.index_to_key

In [37]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [38]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [39]:
X

array([[ 0.36896044,  0.20907629,  0.0497495 ],
       [ 0.3961687 ,  0.03255206,  0.12045513],
       [-0.49996126,  0.0851109 ,  0.06127352],
       ...,
       [-0.0203834 , -0.04176837, -0.04224145],
       [-0.0071324 ,  0.10321522, -0.14370573],
       [ 0.08934112, -0.08434409,  0.03253704]], dtype=float32)

In [40]:
len(X[0])

3

In [42]:
import plotly.express as px
fig = px.scatter_3d(x = X[200:300, 0], y = X[200:300, 1], z = X[200:300, 2], color = y[200:300])
fig.show()